name: Deploy to EC2

on:
  push:
    branches:
      - laptop-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /home/ubuntu/notebook
            git checkout -f origin/laptop-dev frontend/laptopfrontend/
            sudo systemctl restart nginx
